[project]
name = "dailylog-lib"
version = "0.2.5-dev6"
description = "A minimal logger that will suppress all but first message in a specified time to screen"
dynamic = ["classifiers"]
authors = [
    {name = "Quien Sabe",email = "qs5779@pm.me"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "wtforglib (>=1.1.1,<2.0.0)"
]

[tool.poetry]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: POSIX :: Linux",
  "Typing :: Typed",
]

packages = [
    {include = "dailylog_lib", from = "src"},
    {include = "dailylog_lib/py.typed", from = "src"}
]


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
isort = "^8.0"
black = "^26.3.1"
mypy = "^2.3"
wemake-python-styleguide = "^1.1.0"
flake8-pytest-style = "^2.1.0"
doc8 = "^2.0"
pytest = "^9.0"
pytest-cov = "^7.0"
darglint = "^1.0"
pyfakefs = "^6.0"
ruff = "^0.15.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^9.0"
sphinx-autodoc-typehints = ">=1.24,<4.0"
sphinx-mdinclude = "^0.6.2"
tomli = "^2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
external = ["WPS"]

[tool.black]
target-version = ["py311", "py312", "py313"]

[tool.nitpick]
style = "github://qs5779/devtools/nitpick/nitpick-wtf-style.toml"
